--7 Mostrar Detalle Factura.

CREATE VIEW vw_DetalleFactura AS
SELECT f.IDFACTURA, (p.PNOMBRE||' '||p.PAPELLIDO) nombre, l.NOMBRE libro, df.CANTIDAD, tiob.DESCRIPCION TipoObtencion, f.FECHAREGISTRO, tp.DESCRIPCION tipoPago  FROM Factura f
INNER JOIN DETALLEFACTURA df ON f.IDFACTURA = df.FACTURA_IDFACTURA
INNER JOIN CLIENTE c ON f.CLIENTE_IDCLIENTE = c.IDCLIENTE
INNER JOIN Persona p ON c.PERSONA_IDPERSONA = p.IDPERSONA
INNER JOIN LIBRO l ON df.LIBRO_IDLIBRO = l.IDLIBRO
INNER JOIN TIPOOBTENCION tiob ON f.TIPOOBTENCION_IDTIPOOBTENCION = tiob.IDTIPOOBTENCION
INNER JOIN PAGO pa ON f.PAGO_IDPAGO = pa.IDPAGO
INNER JOIN TIPOPAGO tp ON pa.TIPOPAGO_IDTIPOPAGO = tp.IDTIPOPAGO;