--10 Mostrar los clientes que tiene dos o más telefonos.

CREATE VIEW vw_Clientestelefonos AS
SELECT (p.PNOMBRE||' '||p.PAPELLIDO) nombre, COUNT(t.IDTELEFONO) CantidadTelefonos FROM TELEFONO t
INNER JOIN PERSONA p ON t.PERSONA_IDPERSONA = p.IDPERSONA
INNER JOIN CLIENTE c ON p.IDPERSONA = c.PERSONA_IDPERSONA
GROUP BY p.PNOMBRE||' '||p.PAPELLIDO
HAVING COUNT(t.IDTELEFONO) > 1;