
--TRIGGER 
--BODEGA
CREATE SEQUENCE S_ID_BODEGA
START WITH 1
INCREMENT BY 1;

CREATE OR REPLACE TRIGGER TR_BODEGA
BEFORE INSERT ON BODEGA
FOR EACH ROW
DECLARE
BEGIN
:NEW.idBodega:=S_ID_BODEGA.NEXTVAL;
END;